face_web/face_tech/urls.py
from django.conf.urls import url
from . import views
from . import operate
from . import facial

app_name = 'face_tech'
urlpatterns = [
    # url path, function name, shortcut name

    # ---------------------- views.py -----------------------
    url(r'^$', views.index, name='index'),
    url(r'^getstart', views.get_start, name='get_start'),
    url(r'^apis', views.apis, name='apis'),

    url(r'^imageform', views.image_form, name='image_form'),
    url(r'^projectform', views.project_form, name='project_form'),
    url(r'^loginproject', views.login_project, name='login_project'),
    url(r'^changepassword', views.change_password_form, name='change_password_form'),
    url(r'^projectinfo', views.project_info, name='project_info'),

    url(r'^groupform', views.group_form, name='group_form'),
    url(r'^deletegroupform', views.delete_group_form, name='delete_group_form'),

    url(r'^personform', views.person_form, name='person_form'),
    url(r'^deletepersonform', views.delete_person_form, name='delete_person_form'),
    url(r'^getpersonbygroupform', views.get_person_by_group_form, name='get_person_by_group_form'),
    url(r'^getpersonbyprojectform', views.get_person_by_project_form, name='get_person_by_project_form'),

    url(r'^persontogroupform', views.person_to_group_form, name='person_to_group_form'),
    url(r'^deletepersonfromgroupform', views.delete_person_group_form, name='delete_person_group_form'),

    url(r'^enrollmentform', views.enrollment_form, name='enrollment_form'),
    url(r'^verificationform', views.verification_form, name='verification_form'),

    # ---------------------- operate.py -----------------------
    url(r'^create_project', operate.create_project, name='create_project'),
    url(r'^change_psw', operate.change_password, name='change_password'),
    url(r'^authentication', operate.authentication, name='authentication'),
    url(r'^logout_project', operate.logout_project, name='logout_project'),

    url(r'^create_group', operate.create_group, name='create_group'),
    url(r'^get_groups_by_name', operate.get_groups_by_name, name='get_groups_by_name'),
    url(r'^delete_group', operate.delete_group, name='delete_group'),

    url(r'^create_person', operate.create_person, name='create_person'),
    url(r'^create_json_person', operate.create_json_person, name='create_json_person'),
    url(r'^delete_person', operate.delete_person, name='delete_person'),
    url(r'^get_persons_by_group', operate.get_persons_by_group, name='get_persons_by_group'),
    url(r'^get_all_persons', operate.get_all_persons, name='get_all_persons'),

    url(r'^person_to_group', operate.relate_person_to_group, name='relate_person_to_group'),
    url(r'^remove_person_from_group', operate.delete_person_from_group, name='delete_person_from_group'),

    # ---------------------- facial.py -----------------------
    url(r'^detect', facial.detect, name='detect'),
    url(r'^landmark', facial.landmark, name='landmark'),
    url(r'^occluder', facial.occluder, name='occluder'),

    url(r'^check_quality', facial.check_quality, name='check_quality'),
    url(r'^enrollment_faces', facial.enrollment, name='enrollment'),
    url(r'^verification_faces', facial.verification, name='verification'),
]

face_web/face_web/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('face_tech.urls')),
    url(r'^admin/', admin.site.urls),
]

face_web/face_tech/models.py
import datetime
from django.db import models
from .apps import FaceTechConfig
from django.contrib.auth.models import User
from django.core.validators import RegexValidator


class Group(models.Model):
    name = models.CharField(max_length=50, unique=True, validators=[RegexValidator(r'^[\w\s.@+-]+$')])
    description = models.CharField(max_length=200, default='')
    project = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now=True)

    def to_dict(self):
        """ return dictionary of this object """
        _dict = {}
        for f in self._meta.fields:
            if f.name == 'name':
                _dict[f.name] = ''.join(f.value_from_object(self).split('_')[1:])
            else:
                _dict[f.name] = f.value_from_object(self)

        return _dict


class Person(models.Model):
    name = models.CharField(max_length=50, unique=True, validators=[RegexValidator(r'^[\w.@+-]+$')])
    email = models.EmailField(blank=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    note = models.CharField(max_length=200, blank=True)
    project = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now=True)

    def to_dict(self):
        """ return dictionary of this object """
        _dict = {}
        for f in self._meta.fields:
            if f.name == 'name':
                _dict[f.name] = ''.join(f.value_from_object(self).split('_')[1:])
            else:
                _dict[f.name] = f.value_from_object(self)

        return _dict

    def __str__(self):
        return str(self.id)


class Person_To_Group(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)


class Face(models.Model):
    """ save face feature and path. max feature: 10 kb """
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    feature = models.CharField(max_length=10240)
    image = models.ImageField(blank=True, null=True)
    create_date = models.DateTimeField(auto_now=True)


# ----------------Private Functions-------------------

def get_real_name(name, project):
    return '{0}_{1}'.format(project.id, name)


def add_or_get_person(name, project, email='', first_name='', last_name='', note=''):
    """ add new person to database"""
    person_name = get_real_name(name, project)

    try:
        return Person.objects.get(name=person_name)
    except:
        try:
            person = Person(name=person_name, project=project, email=email,
                            first_name=first_name, last_name=last_name, note=note)
            person.save()

            return person
        except: return None


def add_or_get_group(name, project, description=''):
    """ add new person to database"""
    group_name = get_real_name(name, project)
    try:
        return Person.objects.get(name=group_name)
    except:
        try:
            group = Group(name=group_name, project=project, description=description)
            group.save()

            return group
        except:
            return None


def auth_project_seckey(id, key):
    """ Authenticate security key from project name """
    try:
        project = User.objects.get(id=id)

        if project.last_name == key:
            return project
    except: pass

    return False


def get_group_from_project(group_id, project):
    """ From project object and group id to get group ojbect
    If this group not belong to project, return None"""
    try:
        group = Group.objects.get(id=group_id, project=project)
        return group
    except:
        return None


def get_persons_from_project_by_ids(person_id, project):
    """ From project object and person id to get person ojbect
    If this person not belong to project, return None"""
    try:
        if type(person_id) is int:
            person = Person.objects.get(id=person_id, project=project)
            return person
        else:
            persons = []
            for p in person_id:
                persons.append(Person.objects.get(id=p, project=project))
            return persons
    except:
        return None


def get_image_path(person):
    return '{0}/{1}/{2}_{3}.jpg'.format(FaceTechConfig.FACE_FOLDER, person.project_id, person.id,
                                            datetime.datetime.now().strftime("%y%m%d%H%M%S"))

face_web/face_tech/views.py
from . import forms
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect


def index(request):
    message = ""
    if 'message' in request.GET:
        message = request.GET['message']

    return render(request, 'face_tech/index.html', {'message': message})


def get_start(request):
    return render(request, 'face_tech/getstart.html')


def apis(request):
    return render(request, 'face_tech/apis.html')


def image_form(request):
    form = forms.MultiPurposeForm()
    return render(request, 'face_tech/form.html', {'url': 'face_tech:check_quality', 'message': 'Face Detection', 'form': form})


def project_form(request):
    form = forms.ProjectForm()
    return render(request, 'face_tech/form_csrf.html', {'url': 'face_tech:create_project',
                                                     'message': 'Create project form', 'form': form})


def login_project(request):
    form = forms.LoginProjectForm()
    return render(request, 'face_tech/form_csrf.html', {'url': 'face_tech:authentication',
                                                     'message': 'Login Project Form', 'form': form})


@login_required(login_url='/face_tech/loginproject')
def change_password_form(request):
    form = PasswordChangeForm(user=request.user)
    return render(request, 'face_tech/form_csrf.html', {'url': 'face_tech:change_password',
                                                     'message': 'Create project form', 'form': form})


@login_required(login_url='/face_tech/loginproject')
def project_info(request):
    return render(request, 'face_tech/about.html', {'message': 'Project Profile'})


def group_form(request):
    form = forms.GroupForm()
    return render(request, 'face_tech/form.html', {'url': 'face_tech:create_group',
                                                'message': 'Create group form', 'form': form})


def delete_group_form(request):
    form = forms.DeleteGroupForm()
    return render(request, 'face_tech/form.html', {'url': 'face_tech:delete_group',
                                                'message': 'Delete group form', 'form': form})


def person_form(request):
    form = forms.PersonForm()
    return render(request, 'face_tech/form.html', {'url': 'face_tech:create_person',
                                                'message': 'Create person form (only numbers, letters and .@;+- will be allowed, '
                                                           + '";" is used to separate different persons)',
                                                'form': form})


def get_person_by_group_form(request):
    form = forms.PersonByGroupForm()
    return render(request, 'face_tech/form.html', {'url': 'face_tech:get_persons_by_group',
                                                'message': 'Get persons by group id', 'form': form})


def get_person_by_project_form(request):
    form = forms.PersonByProjectForm()
    return render(request, 'face_tech/form.html', {'url': 'face_tech:get_all_persons',
                                                'message': 'Get persons by Project', 'form': form})


def delete_person_form(request):
    form = forms.DeletePersonForm()
    return render(request, 'face_tech/form.html', {'url': 'face_tech:delete_person',
                                                'message': 'Delete person form (";" is used to separate different person ids)',
                                                'form': form})


def person_to_group_form(request):
    form = forms.PersonToGroupForm()
    return render(request, 'face_tech/form.html', {'url': 'face_tech:relate_person_to_group',
                                                'message': 'Add persons to group form. '
                                                           + 'Use ";" to separate different persons.', 'form': form})


def delete_person_group_form(request):
    form = forms.PersonToGroupForm()
    return render(request, 'face_tech/form.html', {'url': 'face_tech:delete_person_from_group',
                                                'message': 'Delete persons from group form. '
                                                           + 'Use ";" to separate different persons.', 'form': form})


def enrollment_form(request):
    form = forms.EnrollmentForm()
    return render(request, 'face_tech/form.html', {'url': 'face_tech:enrollment',
                                                'message': 'Enrollment form.', 'form': form})


def verification_form(request):
    form = forms.VerificationForm()
    return render(request, 'face_tech/form.html', {'url': 'face_tech:verification',
                                                'message': 'Verification form.', 'form': form})


# ----------------Private Functions-------------------

def redirect_index(message):
    return HttpResponseRedirect(reverse('face_tech:index') + '?message=' + message)


def error_response(error_code, name='', message=''):
    error_message = {
        0: '{}: {}'.format(name, message),
        1: 'Error: {} Invalid input. {}'.format(name, message),
        2: 'Project or security key is Invalid.',
        3: 'Group does not exist or belong to your project {}'.format(name),
        4: 'Persons do not exist or belong to your project {}'.format(name),
        5: 'No face detected in image.',
    }

    response = HttpResponse(error_message.get(error_code))
    response.status_code = 406
    return response

face_web/face_tech/templates/face_tech/about.html
{% include "face_tech/header.html" %}
<div class="page-header">
    <h3>{{ message|escape}}</h3>
</div>

{% include "face_tech/footer.html" %}

face_web/face_tech/templates/face_tech/apis.html
{% load staticfiles %}
{% include "face_tech/header.html" %}
<link href="{% static 'bootstrap/css/docs.css' %}" rel="stylesheet">

<div class="container">
    {% include "face_tech/footer.html" %}
</div>

face_web/face_tech/templates/face_tech/fileform.html
{% load staticfiles %}
{% include "face_tech/header.html" %}
<div class="page-header">
    <h3>{{ message|escape}}</h3>
</div>
{% if error_message %}<p><strong>{{ error_message|escape }}</strong></p>{% endif %}

<form action="{% url 'myapp:detect' %}" method="post" enctype="multipart/form-data">
    <input id="id_title" maxlength="50" name="title" type="text">
    <input id="id_image" name="image" type="file">
    <input type="submit" value="Submit" />
</form>

{% include "face_tech/footer.html" %}

face_web/face_tech/templates/face_tech/footer.html
    <hr>

      <footer>
        <p>&copy; Company 2016</p>
      </footer>


</body>
</html>

face_web/face_tech/templates/face_tech/getstart.html
{% load staticfiles %}
<link href="{% static 'css/docs.css' %}" rel="stylesheet">
<link href="{% static 'css/highlight.css' %}" rel="stylesheet">
{% include "face_tech/header.html" %}

<style>h2{
    margin-top: -40px;
    padding-top: 60px;
}</style>
<div class="container">
    <div class="row">
        <div class="col-md-3 bs-docs-sidebar">
            <ul class="nav nav-list bs-docs-sidenav affix">
              <li class=""><a href="#create-a-project">Create a project</a></li>
              <li class=""><a href="#download">Download</a></li>
              <li class=""><a href="#initial">Initial</a></li>
              <li class=""><a href="#person"><i class="icon-chevron-right"></i> Person</a></li>
              <li class=""><a href="#group"><i class="icon-chevron-right"></i> Group</a></li>
              <li class=""><a href="#person-to-group"><i class="icon-chevron-right"></i> Person to Group</a></li>
              <li class=""><a href="#detect-faces-and-landmarks"><i class="icon-chevron-right"></i> Detect faces and landmarks</a></li>
              <li class=""><a href="#face-recognition"><i class="icon-chevron-right"></i> Face recognition</a></li>
            </ul>
        </div>

        <div class="col-md-8" role="main">
            <div class="page-header" style="margin-bottom: 0">
                <h1>Getting Started</h1>
            </div>

            <!-- ------------ Generate from mkdocs -------------
                Copy from browser after serve mkdocs, then correct the link href.
            -->

<h2 id="create-a-project">Create a project</h2>
<p>Before you get started, click <a href="{% url 'face_tech:project_form' %}">here</a> to register a new project.</p>
<p>After sign in you will get your project and security key, it will be used for </p>
<ul>
<li>Use face APIs</li>
<li>Create groups or persons to your project</li>
<li>Enroll faces with identification to your project</li>
<li>Verify faces from your project</li>
</ul>
<p>You can login your project to check status of groups and persons.</p>
<p><code>Tips: Groups are belong to one project, they are used to separate persons into different groups.</code>
<code>One person may belong to several groups and enroll many times to server.</code></p>
<h2 id="download">Download</h2>
<p>Click <a href="{% static 'face_tech.py' %}">here</a> to download face_tech.py, no need to install, just make sure you have install the following.</p>
<pre><code class="hljs vala"><span class="hljs-preprocessor"># Python3</span>
sudo apt-<span class="hljs-keyword">get</span> install python3

<span class="hljs-preprocessor"># Requests</span>
pip install requests

<span class="hljs-preprocessor"># Requests toolbelt</span>
pip install requests-toolbelt
</code></pre>
<h2 id="initial">Initial</h2>
<p>The main object is FaceAPI, it create connection between your project and the face server. Now you can call functions to do your project.</p>
<pre><code class="hljs capnproto"><span class="hljs-keyword">from</span> face_tech <span class="hljs-keyword">import</span> FaceAPI
</code></pre>

<pre><code class="hljs stylus">project_key = <span class="hljs-string">'your project key'</span>
security_key = <span class="hljs-string">'your security key'</span>

api = <span class="hljs-function"><span class="hljs-title">FaceAPI</span><span class="hljs-params">(project_key, security_key)</span></span>
</code></pre>
<h2 id="group">Group</h2>
<p>Create a new group with provided group name, and you can provide optional description to specify this group. This function will return the new group’s id.</p>
<pre><code class="hljs stylus">r = api.<span class="hljs-function"><span class="hljs-title">create_group</span><span class="hljs-params">(name=<span class="hljs-string">'new group'</span>, desc=’create by Jim’)</span></span>
<span class="hljs-function"><span class="hljs-title">print</span><span class="hljs-params">(r)</span></span>
</code></pre>
<p>The name may contain only letters, numbers, ' ' and @/./+/-/_ characters, make sure name is unique in your project.</p>
<p>Pass the group id to delete_group to delete the group you just created. This will return a boolean to tell you if it is successfully deleted.</p>
<pre><code class="hljs stylus">r = api.<span class="hljs-function"><span class="hljs-title">delete_group</span><span class="hljs-params">(group=<span class="hljs-number">1</span>)</span></span>
<span class="hljs-function"><span class="hljs-title">print</span><span class="hljs-params">(r)</span></span>
</code></pre>
<h2 id="person">Person</h2>
<p>To create a new person, use create_person and provide new names you want. If new persons belong to a group you just created, pass group id to this function, it will create the relation with new persons with group. Additional email, first name, last name and note is optional while creating new person.</p>
<pre><code class="hljs stylus">r = api.create_person(name=<span class="hljs-string">'james'</span>, email=<span class="hljs-string">'test@test.com'</span>,
                      first_name=<span class="hljs-string">'James'</span>, last_name=<span class="hljs-string">'Smith'</span>,
                      note=<span class="hljs-string">'freshman'</span>, group=<span class="hljs-number">2</span>)
<span class="hljs-function"><span class="hljs-title">print</span><span class="hljs-params">(r)</span></span>
</code></pre>
<p>This will return a list of person id if no error. The name may contain only letters, numbers and @/./+/-/_ characters, and should be unique in your project. All these fields except 'group' can be list to create multiple persons at one time.</p>
<p>Or use create_person_json for creating person by json format, provide json format 'data' param and additional group id.</p>
<p>To get all persons exist in your project or a group, use following function to retrieve, where group should be the group id.</p>
<pre><code class="hljs stylus">r = api.<span class="hljs-function"><span class="hljs-title">get_persons_by_group</span><span class="hljs-params">(group=<span class="hljs-number">1</span>)</span></span>

r = api.<span class="hljs-function"><span class="hljs-title">get_all_persons</span><span class="hljs-params">()</span></span>

<span class="hljs-function"><span class="hljs-title">print</span><span class="hljs-params">(r)</span></span>
</code></pre>
<p>To delete a person, you only have to provide person id you get when you created it. And it will return [{‘person_id’: True or False}], where False means you do not have the permission to delete because this person does not belong to your project, or this person does not exist. 'person' can be a list of person ids to delete multiple persons at one time.</p>
<pre><code class="hljs stylus">r = api.<span class="hljs-function"><span class="hljs-title">delete_person</span><span class="hljs-params">(person=<span class="hljs-number">1</span>)</span></span>
<span class="hljs-function"><span class="hljs-title">print</span><span class="hljs-params">(r)</span></span>
</code></pre>
<h2 id="person-to-group">Person to Group</h2>
<p>If you have several groups in your project, you probably want to relate some persons to groups. Persons do not have to belong to any group, but it is good to divide them to speed up the searching process. </p>
<p>If you assign a group id when you create new persons, you do not need to related them together again as below.</p>
<pre><code class="hljs stylus">r = api.<span class="hljs-function"><span class="hljs-title">person_to_group</span><span class="hljs-params">(person=<span class="hljs-number">12</span>, group=<span class="hljs-number">2</span>)</span></span>
</code></pre>
<p>This will return a list of numbers instead of False, which means the row id of this relationship in server. Make sure all person ids are valid and belong to your project. 'person' can be list to relate many persons to one group at one time.</p>
<p>All parameters are the same as above when delete the relation by using remove_person_from_group.</p>
<h2 id="detect-faces-and-landmarks">Detect faces and landmarks</h2>
<p>You only need provide a valid image, detect function will return a list of face coordinates, which refer to [top, bottom, left, right]. Landmark detection will return all landmark coordinates and face coordinates.</p>
<pre><code class="hljs gradle"><span class="hljs-keyword">from</span> face_tech <span class="hljs-keyword">import</span> <span class="hljs-keyword">file</span>
</code></pre>

<pre><code class="hljs mel">img = <span class="hljs-string">"image/sample.jpg"</span>

r = api.detect(<span class="hljs-keyword">image</span>=<span class="hljs-keyword">file</span>(img))
<span class="hljs-keyword">print</span>(r)
&gt;&gt; [[<span class="hljs-number">74</span>, <span class="hljs-number">173</span>, <span class="hljs-number">312</span>, <span class="hljs-number">398</span>], [<span class="hljs-number">107</span>, <span class="hljs-number">198</span>, <span class="hljs-number">86</span>, <span class="hljs-number">165</span>]]

r = api.landmark(<span class="hljs-keyword">image</span>=<span class="hljs-keyword">file</span>(img))
<span class="hljs-keyword">print</span>(len(r))
&gt;&gt; [{<span class="hljs-string">'landmarks'</span>: [[<span class="hljs-number">303</span>, <span class="hljs-number">108</span>], [<span class="hljs-number">302</span>, <span class="hljs-number">121</span>] .. , <span class="hljs-string">'coordinates'</span>: [<span class="hljs-number">115</span>, <span class="hljs-number">205</span>, <span class="hljs-number">85</span>, <span class="hljs-number">174</span>]}, ..]

r = api.occluder(<span class="hljs-keyword">image</span>=<span class="hljs-keyword">file</span>(img))
<span class="hljs-keyword">print</span>(r)
&gt;&gt; [{<span class="hljs-string">'occlude'</span>: True, <span class="hljs-string">'coordinates'</span>: [<span class="hljs-number">78</span>, <span class="hljs-number">186</span>, <span class="hljs-number">293</span>, <span class="hljs-number">400</span>]}, ..]
</code></pre>
<h2 id="face-recognition">Face recognition</h2>
<p>Before you want to recognize faces from images, you have to enroll faces into server. Provide a json format data to specify each person id and its face coordinates, then you can verify these persons next time. Group id is optional if this person does not belong to any group.</p>
<pre><code class="hljs powershell"><span class="hljs-comment"># specify person_id with face coordinates</span>
<span class="hljs-keyword">data</span> = {<span class="hljs-string">"faces"</span>: [{<span class="hljs-string">"person_id"</span>:<span class="hljs-number">63</span>, <span class="hljs-string">"coordinates"</span>: [<span class="hljs-number">78</span>, <span class="hljs-number">186</span>, <span class="hljs-number">293</span>, <span class="hljs-number">400</span>]}]}
</code></pre>

<pre><code class="hljs stylus">r = api.<span class="hljs-function"><span class="hljs-title">enrollment_faces</span><span class="hljs-params">(data=data, image=file(img)</span></span>, group=<span class="hljs-number">2</span>)
<span class="hljs-function"><span class="hljs-title">print</span><span class="hljs-params">(r)</span></span>
</code></pre>
<p>Or you can call check_quality every time before you enroll faces, this will tell you the quality of image you provided, retake a photo to improve the result.</p>
<pre><code class="hljs stylus">r = api.<span class="hljs-function"><span class="hljs-title">check_quality</span><span class="hljs-params">(image=file(img)</span></span>, data=False)
<span class="hljs-function"><span class="hljs-title">print</span><span class="hljs-params">(r)</span></span>
</code></pre>
<p>If data is True, it means it will return a filename which stored in sever. Just pass the result with person ids to enrollment_faces, you do not need to pass a whole image again.</p>
<p>After you enroll faces to server, it’s time to verify them from photos.</p>
<pre><code class="hljs stylus">r = api.<span class="hljs-function"><span class="hljs-title">verification_faces</span><span class="hljs-params">(image=file(img)</span></span>, group=<span class="hljs-number">2</span>)
<span class="hljs-function"><span class="hljs-title">print</span><span class="hljs-params">(r)</span></span>
</code></pre>
<p>Group id is optional when verify, and it will return person id as following.</p>
<pre><code class="hljs prolog">&gt;&gt; [{<span class="hljs-string">'person_id'</span>: <span class="hljs-number">34</span>, <span class="hljs-string">'name'</span>: <span class="hljs-name">Jim</span>, <span class="hljs-string">'first_name'</span>: <span class="hljs-string">'Jim'</span>, <span class="hljs-string">'last_name'</span>: <span class="hljs-string">'Smith'</span>, <span class="hljs-string">'email'</span>: <span class="hljs-string">'test@test.com'</span>, <span class="hljs-string">'note'</span>: <span class="hljs-string">'freshman'</span>, <span class="hljs-string">'coordinates'</span>: [<span class="hljs-number">78</span>, <span class="hljs-number">186</span>, <span class="hljs-number">293</span>, <span class="hljs-number">400</span>]}, {<span class="hljs-string">'person_id'</span>: <span class="hljs-string">'None'</span>, <span class="hljs-string">'coordinates'</span>: [<span class="hljs-number">175</span>, <span class="hljs-number">264</span>, <span class="hljs-number">214</span>, <span class="hljs-number">304</span>]}]
</code></pre>
<p>If there is no match identification in record, the person_id will be None.</p>




        <!-- ----------------- End of mkdocs -------------------- -->

        </div>
    </div>
    {% include "face_tech/footer.html" %}
</div>

face_web/face_tech/templates/face_tech/header.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Face Website</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="Face algorithm website, provide face algorithm API">
    <meta name="author" content="Charmy Feng">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}" rel="stylesheet">
    <style>body{padding-top: 40px}</style>
</head>
<body role="document">
    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a  class="navbar-brand" style="color:#ffffff" href="{% url 'face_tech:index' %}">Face Tech</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
              <li class=""><a href="{% url 'face_tech:get_start' %}">Getting Started</a></li>
              <li><a href="{% url 'face_tech:apis' %}">APIs</a></li>
            <li><a href="#about">About</a></li>
            <!--li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li-->
          </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a><span class="glyphicon glyphicon-user"></span> {{ user.first_name }}</a></li>
                    <li><a href="{% url 'face_tech:logout_project' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'face_tech:project_form' %}">Sign in</a></li>
                    <li><a href="{% url 'face_tech:login_project' %}">Log in</a></li>
                {% endif %}
            </ul>

        </div><!--/.nav-collapse -->
      </div>
    </nav>