attendence/attend_server/urls.py
from . import views
from . import ivle_views
from . import attend_views
from django.conf.urls import url


app_name = 'attend'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^form_update_module', views.update_module_form, name='update_module'),
    url(r'^form_detect', views.detection, name='detect_form'),
    url(r'^form_new_module', views.module_form, name='module_form'),
    url(r'^form_new_tutor', views.tutor_form, name='tutor_form'),
    url(r'^form_student', views.student_form, name='student_form'),
    url(r'^signin', views.create_user_form, name='create_user_form'),
    url(r'^login', views.login_form, name='login_form'),
    url(r'^form_tutor_add_student', views.tutor_add_student_form, name='form_tutor_add_student'),

    url(r'^logout', views.log_out, name='log_out'),
    url(r'^user_logout', views.user_logout, name='user_logout'),
    url(r'^register', views.sign_in, name='sign_in'),
    url(r'^user_index', views.user_index, name='user_index'),
    url(r'^detect', views.face_detection, name='detect'),
    url(r'^enrollment', views.enrollment, name='enrollment'),
    url(r'^verify', views.verify, name='verify'),
    url(r'^attendance', views.attend, name='attend'),
    url(r'^create_module', views.create_module, name='create_module'),
    url(r'^create_student', views.create_student, name='create_student'),
    url(r'^add_tutor', views.add_tutor, name='add_tutor'),
    url(r'^tutor_add_student', views.tutor_add_student, name='tutor_add_student'),
    url(r'^view', views.view_module, name='view_module'),

    url(r'^attend_login', attend_views.log_in, name='attend_login'),
    url(r'^attend_module', attend_views.update_module, name='attend_module'),

    url(r'^ivle_login', ivle_views.log_in, name='ivle_login'),
    url(r'^ivle_module', ivle_views.update_module, name='update_module'),
]

attendence/attendence/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('attend_server.urls')),
    url(r'^admin/', admin.site.urls),
]

attendence/attend_server/forms.py
from django import forms
from django.core.validators import RegexValidator


class LoginForm(forms.Form):
    """ User login form: userid and encoded password """
    option = forms.ChoiceField(choices=(('default', 'Default'), ('ivle', 'NUS IVLE')), required=False)
    username = forms.CharField(max_length=30, label='User Name')
    password = forms.CharField(widget=forms.PasswordInput())


class DataForm(forms.Form):
    """ data usually is dict, token is AuthToken fetch from IVLE """
    data = forms.CharField()
    token = forms.CharField(max_length=500, label='Auth Token', required=False)
    group = forms.IntegerField(label='Group ID', required=False)
    module = forms.CharField(label='Module ID', required=False)
    # cg = forms.BooleanField(label='class or guest', required=False)
    lt = forms.BooleanField(label='lecture or tutorial', required=False)
    owner = forms.CharField(label='Owner', required=False)
    time_id = forms.IntegerField(label='Time ID', required=False)


class ImgForm(forms.Form):
    """ Provide img with data """
    image = forms.ImageField()
    data = forms.CharField(required=False, label='Data (optional)')
    group = forms.IntegerField(label='Group ID', required=False)
    module = forms.CharField(label='Module ID', required=False)
    lt = forms.BooleanField(label='lecture or tutorial', required=False)
    owner = forms.IntegerField(widget = forms.HiddenInput())


class ModuleForm(forms.Form):
    """ create a new module form """
    code = forms.CharField(label='Module Code', max_length=50)
    name = forms.CharField(label='Module Name', max_length=100)
    year = forms.CharField(label='Academic Year', max_length=20, required=False)
    semester = forms.CharField(label='Semester', max_length=100, required=False)

class TutorForm(forms.Form):
    """ add a tutor to a module """
    module = forms.IntegerField(widget=forms.HiddenInput())
    name = forms.CharField(label='Tutor Name', max_length=50, validators=[RegexValidator(r'^[\w.@+-]+$')])
    
class StudentForm(forms.Form):
    """ add student form """
    module = forms.IntegerField(widget=forms.HiddenInput())
    name = forms.CharField(label='Name (unique)', max_length=50, validators=[RegexValidator(r'^[\w.@+-]+$')])
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(required=False)
    note = forms.CharField(max_length=200, required=False)

    # def __init__(self, custom_choices=None, *args, **kwargs):
    #     super(StudentForm, self).__init__(*args, **kwargs)
    #     if custom_choices:
    #         self.fields['module'].choices = custom_choices

class TutorStudentForm(forms.Form):
    """ tutor add student form """
    module = forms.IntegerField(widget=forms.HiddenInput())
    search_name = forms.CharField(label='Search', max_length=50, required=False)

    def __init__(self, *args, **kwargs):
        student_list = kwargs.pop('student_list')
        super(TutorStudentForm, self).__init__(*args, **kwargs)
        CHOICES = ()
        for s in student_list:
            if len(CHOICES)>0:
                CHOICES = CHOICES + ((s['name'], s['first_name']), )
            else:
                CHOICES = ((s['name'], s['first_name']), )

        self.fields['checklist'] = forms.MultipleChoiceField(
            required=False, 
            widget=forms.CheckboxSelectMultiple(), 
            choices=CHOICES,
         )

        

attendence/attend_server/views.py
from . import models
from shutil import copyfile
from .face_tech import file
from django.shortcuts import render
from .apps import api, error_response
from django.contrib.auth import logout
import logging, traceback, json, os, time
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from . import forms, ivle_views, attend_views
from django.core.files.base import ContentFile
from django.http import JsonResponse, HttpRequest
from django.contrib.auth import authenticate, login
from django.views.decorators.csrf import csrf_exempt
from django.core.files.storage import default_storage
from django.contrib.auth.forms import UserCreationForm

log = logging.getLogger(__name__)


def index(request):
    message = ""
    if 'message' in request.GET:
        message = request.GET['message']

    return render(request, 'attend/index.html', {'url': 'attend:sign_in', 'message': message})


def create_user_form(request):
    form = UserCreationForm()
    return render(request, 'attend/form_csrf.html', {'url': 'attend:sign_in', 'title': 'Sign in Form', 'form': form})


def login_form(request):
    form = forms.LoginForm()
    return render(request, 'attend/form_csrf.html', {'url': 'attend:user_index', 'title': 'Login Form', 'form': form})


def update_module_form(request):
    form = forms.DataForm()
    return render(request, 'attend/form.html', {'url': 'attend:update_module', 'title': 'update_module Form', 'form': form})


def detection(request):
    form = forms.ImgForm()
    return render(request, 'attend/form.html', {'url': 'attend:detect', 'title': 'Img Form', 'form': form})


def sign_in(request):
    form = UserCreationForm(request.POST)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('attend:user_index'))

    return render(request, 'attend/form_csrf.html', {'url': 'attend:sign_in', 'title': 'Sign in Form', 'form': form})


def user_index(request):
    if (request.user.is_authenticated() or 'ivle_user' in request.session) and 'Modules' in request.session:
        return render(request, 'attend/user.html', {'html': 'attend/profile.html', 'modules': request.session['Modules'],
                                             'message': request.GET['message'] if 'message' in request.GET else ''})

    else:
        form = forms.LoginForm(request.POST)
        message = 'please login.'

        if form.is_valid():
            response = None
            option = form.cleaned_data['option']

            if option == 'default':
                response = attend_views.log_in(request)
            elif option == 'ivle':
                response = ivle_views.log_in(request)

            # if response is valid show user index
            if response and response.status_code == 200:
                response = get_content(response)

                if option == 'ivle':
                    request.session['ivle_user'] = {'username': response['Name'],
                                                    'authToken': response['authToken']}
                elif option == 'default':
                    login(request, authenticate(username=form.cleaned_data['username'],
                                                password=form.cleaned_data['password']))

                request.session['Modules'] = response['Modules']
                return redirect_index('Login Success')
            else:
                message = response.content.decode("utf-8")

        return render(request, 'attend/form_csrf.html', {'url': 'attend:user_index', 'title': 'Login Form',
                                                  'message': message, 'form': form})


def user_logout(request):
    print("logging out")
    if request.user.is_authenticated():
        logout(request)
    return JsonResponse({'data': 'success'})

def log_out(request):
    if request.user.is_authenticated():
        logout(request)

    if 'ivle_user' in request.session:
        del request.session['ivle_user']

    return redirect_index('Log out')


def module_form(request):
    form = forms.ModuleForm()
    return render(request, 'attend/form_csrf.html', {'url': 'attend:create_module', 'title': 'Create Module', 'form': form})

def create_module(request):
    form = forms.ModuleForm(request.POST)

    if form.is_valid() and request.user.is_authenticated():
        print("login");
        try:
            code = form.cleaned_data['code']
            group = api.get_groups_by_name(name=code)

            # avoid duplicate group name
            while group:
                code = form.cleaned_data['code'] + models.get_suffix()
                group = api.get_groups_by_name(name=code)

            group_id = api.create_group(name=code, desc=form.cleaned_data['name'])

            m = models.Modules(code=code, group_id=group_id, name=form.cleaned_data['name'],
                               academic_year=form.cleaned_data['year'], semester=form.cleaned_data['semester'])
            m.save()
            
            ump, is_exist = models.User_Module_Permission.objects.get_or_create(user=request.user, module=m, permission='F')

            m = m.to_dict()
            m['Permission'] = ump.permission
            request.session['Modules'].append(m)

            return HttpResponseRedirect(reverse('attend:user_index'))
        except:
            log.error(traceback.format_exc())

    return render(request, 'attend/form_csrf.html', {'url': 'attend:create_module', 'title': 'Create Module', 'form': form})

def tutor_form(request):
    """ Create tutor form """
    if request.user.is_authenticated():
        # choice = tuple([(m.module.id, m.module.code + ' ' + m.module.name) for m in models.get_user_modules(request)])
        form = forms.TutorForm({'module':request.session['cur_module_id']})

        return render(request, 'attend/form_csrf.html', {'url': 'attend:add_tutor', 'title': 'Add Tutor', 'form': form})

    return HttpResponseRedirect(reverse('attend:user_index'))

def add_tutor(request):
    form = forms.TutorForm(request.POST)

    if form.is_valid() and request.user.is_authenticated():
        try:
            module = models.Modules.objects.filter(id=form.cleaned_data['module'])
            tutor = models.get_user(form.cleaned_data['name'])

            if module:
                if tutor:
                    ump, is_exist = models.User_Module_Permission.objects.get_or_create(user=tutor[0], module=module[0], defaults={'permission':'M'})

                    return HttpResponseRedirect(reverse('attend:view_module') + '?id=' + str(module[0].id))
                else:
                    message = 'Unknown Tutor.'
            else:
                message = 'Unknown Module.'
        except:
            log.error(traceback.format_exc())
            message = 'This student name is already exist.'

        return render(request, 'attend/form_csrf.html', {'url': 'attend:add_tutor', 'title': 'Add tutor', 'form': form,
                                                  'message': message})
    else:
        return HttpResponseRedirect(reverse('attend:user_index'))

def tutor_add_student_form(request):
    if request.user.is_authenticated():
        my_ss = [ts.student.name for ts in models.get_my_student_in_module(request.user, request.session['cur_module_id'])]
        all_ss = [s.to_dict() for s in models.get_all_students_in_module(request.session['cur_module_id'])]
        initial_val = [all_ss[i]['name'] for i in range(len(all_ss)) if all_ss[i]['name'] in my_ss]

        form = forms.TutorStudentForm({'module':request.session['cur_module_id'], 'checklist': initial_val}, student_list=all_ss)

        return render(request, 'attend/form_csrf.html', {'url': 'attend:tutor_add_student', 'title': 'Add My Students', 'form': form, 'message': 'Search name or Check name'})

def tutor_add_student(request):
    if request.user.is_authenticated():
        my_st = [st for st in models.get_my_student_in_module(request.user, request.session['cur_module_id'])]
        all_ss = [s for s in models.get_all_students_in_module(request.session['cur_module_id'])]

        form = forms.TutorStudentForm(request.POST, student_list=[s.to_dict() for s in all_ss])

        if form.is_valid():
            module = models.Modules.objects.filter(id=form.cleaned_data['module'])
            new_student_list = [s for s in models.Student.objects.filter(name=form.cleaned_data['search_name'])]
            [new_student_list.append(s) for s in models.Student.objects.filter(name__in=form.cleaned_data['checklist'])]
            
            # add the relation with minimal overhead
            # delete ones not in the new student list
            for s in new_student_list:
                st, is_new = models.Tutor_Students.objects.get_or_create(tutor=request.user, student=s, module=module[0])
                if st in my_st:
                    my_st.remove(st)
            if my_st:
                [st.delete() for st in my_st]

            return HttpResponseRedirect(reverse('attend:view_module') + '?id=' + str(module[0].id))
            
    return HttpResponseRedirect(reverse('attend:user_index'))

def student_form(request):
    """ Create student form """
    if request.user.is_authenticated():
        # choice = tuple([(m.module.id, m.module.code + ' ' + m.module.name) for m in models.get_user_modules(request)])
        form = forms.StudentForm({'module': request.session['cur_module_id']})

        return render(request, 'attend/form_csrf.html', {'url': 'attend:create_student', 'title': 'Add Student', 'form': form})

    return HttpResponseRedirect(reverse('attend:user_index'))


def create_student(request):
    form = forms.StudentForm(request.POST)

    if form.is_valid() and request.user.is_authenticated():

        module = models.Modules.objects.filter(id=form.cleaned_data['module'])
        try:
            if module:
                student = models.Student(module=module[0], name=form.cleaned_data['name'],

attendence/attend_server/templates/attend/footer.html
    <hr>

      <footer>
        <p>&copy; 2016 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>


</body>
</html>

attendence/attend_server/templates/attend/form.html
{% load staticfiles %}
{% include "attend/header.html" %}

<div class="container">

    <div class="page-header">
        <h3>{{ title|escape}}</h3>
    </div>
    {% if message %}<p><span class="alert alert-warning"><strong>{{ message|escape }}</strong></span></p><br/>{% endif %}

    <div>
        <form action="{% url url %}" method="post" enctype="multipart/form-data">
            {{ form }}
            <br/><input type="submit" value="Submit" />
        </form>
    </div>

    {% include "attend/footer.html" %}
</div>

attendence/attend_server/templates/attend/form_csrf.html
{% load staticfiles %}
{% include "attend/header.html" %}
<style>
    input, select{
        display: block;
        margin-bottom: 10px;
    }
</style>
<div class="container">

    <div class="page-header">
        <h3>{{ title|escape}}</h3>
    </div>
    {% if message %}<p><span class="alert alert-warning"><strong>{{ message|escape }}</strong></span></p><br/>{% endif %}

    <section>
        <form action="{% url url %}" method="post">
            {% csrf_token %}
            {{ form }}
            <br/><input type="submit" value="Submit" />
        </form>
    </section>

{% include "attend/footer.html" %}
</div>

attendence/attend_server/templates/attend/header.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Attendance</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="Face algorithm website, provide face algorithm API">
    <meta name="author" content="Charmy Feng">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
    <style>body{padding-top: 40px}</style>
</head>
<body role="document">
    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a  class="navbar-brand" style="color:#ffffff" href="/">Attendance</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <!--li class=""><a href="">Getting Started</a></li>
            <li><a href="">APIs</a></li>
            <li><a href="#about">About</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li-->
          </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated or 'ivle_user' in request.session%}
                    <li><a href="{% url 'attend:user_index' %}"><span class="glyphicon glyphicon-user"></span>
                        {{ user.username }}{{ request.session.ivle_user.username }}
                    </a></li>
                    <li><a href="{% url 'attend:log_out' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'attend:create_user_form' %}">Sign in</a></li>
                    <li><a href="{% url 'attend:login_form' %}">Log in</a></li>
                {% endif %}
            </ul>

        </div><!--/.nav-collapse -->
      </div>
    </nav>

attendence/attend_server/templates/attend/index.html
{% load staticfiles %}
{% include "attend/header.html" %}
<!-- Custom styles for this template -->
<link href="{% static 'carousel.css' %}" rel="stylesheet">
    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Take Attendance in Class</h1>
              <p>Enroll every student of your class, then you can take the attendance by this app. No more extra time just take a photo.</p>
              <p><a class="btn btn-lg btn-primary" role="button" href="{% url 'attend:create_user_form' %}">Sign up today</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Group Union</h1>
              <p>Save every photo of parties, for beautiful memory.</p>
              <p><a class="btn btn-lg btn-primary" href="{% static 'android-debug.apk' %}" role="button">Download</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Statistic Report</h1>
              <p>Professional statistic table and chart are provided via web page, you can download anytime.</p>
              <p><a class="btn btn-lg btn-primary" href="{% url 'attend:user_index' %}" role="button">Browse gallery</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">
      {% if message %}<p><span class="alert alert-warning"><strong>{{ message|escape}}</strong></span></p><br/>{% endif %}
      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
          <img class="img-circle" src="{% static 'img/ivle.png' %}" alt="Generic placeholder image" width="140" height="140">
          <h2>NUS IVLE</h2>
          <p>If you are Lecturer or TA from National University of Singapore, just login with your NUS user ID and password, and you will see a list of available modules. Let's click below button and start!</p>
          <p><a class="btn btn-default" href="{% url 'attend:login_form' %}" role="button">Login with IVLE &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="{% static 'img/group.gif' %}" alt="Generic placeholder image" width="140" height="140">
          <h2>Create Your Group</h2>
          <p>Create a account here, then you may create a new group and add your students. Multiple statistic report is automatically generate for you.</p><br/>
          <p><a class="btn btn-default" href="{% url 'attend:create_user_form' %}" role="button">Sign in &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="{% static 'img/button.png' %}" alt="Generic placeholder image" width="140" height="140">
          <h2>Take Attendance</h2>
          <p>Download the app and no need to call the roll anymore, let this app to take attendance for you. Just take a photo during class after first enrollment, all attendance are available for you to check.</p>
          <p><a class="btn btn-default" href="{% static 'android-debug.apk' %}" role="button">Download &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->


      <!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7 col-md-push-5">
          <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5 col-md-pull-7">
          <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
      </div>

      <!-- /END THE FEATURETTES -->
    {% include "attend/footer.html" %}

    </div><!-- /.container -->

attendence/attend_server/templates/attend/profile.html
          <h2 class="page-header">{{ user.username }}{{ request.session.ivle_user.username }}'s Modules
              {% if user.is_authenticated %}
                <small><a href="{% url 'attend:module_form' %}" style="font-size: 15px;text-decoration: none;">&nbsp;+ Add module</a></small>
              {% endif %}
          </h2>
          {% if message %}<p><span class="alert alert-warning"><strong>{{ message|escape }}</strong></span></p><br/>{% endif %}

          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Course Code</th>
                  <th>Course Name</th>
                  <th>Academic Year</th>
                  <th>Semester</th>
                </tr>
              </thead>
              <tbody>
                {% if modules %}
                    {% for item in modules %}
                        <tr>
                          <td><a href="{% url 'attend:view_module' %}?id={{ item.ID }}">{{ item.CourseCode }}</a></td>
                          <td><a href="{% url 'attend:view_module' %}?id={{ item.ID }}">{{ item.CourseName }} {{ item.last_name }}</a></td>
                          <td>{{ item.CourseAcadYear }}</td>
                          <td>{{ item.CourseSemester }}</td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td><i>No Module</i></td>
                    </tr>
                {% endif %}
              </tbody>
            </table>
          </div>

attendence/attend_server/templates/attend/user.html
{% load staticfiles %}
{% include "attend/header.html" %}
<!-- Custom styles for this template -->
<link href="{% static 'dashboard.css' %}" rel="stylesheet">

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li {% if not module %}class="active"{% endif %}><a href="{% url 'attend:user_index' %}">Overview</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            {% for item in modules %}
                <li {% if module and module.ID == item.ID %}class="active"{% endif %}>
                    <a href="{% url 'attend:view_module' %}?id={{ item.ID }}">
                    {{ item.CourseCode }} {{ item.CourseName }}</a>

                    {% if module and module.ID == item.ID %}
                      <ul class="nav nav-sidebar" style="padding-left: 35px;margin: 10px 0;">
                        <li><a href="#weekly_chart" style="padding: 5px">Weekly Attendance</a></li>
                        <li><a href="#summary_table" style="padding: 5px">Attendance Summary</a></li>
                        <li><a href="#student_table" style="padding: 5px">Student Attendance</a></li>
                      </ul>
                    {% endif %}
                </li>
            {% endfor %}
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            {% include html %}
        </div>
      </div>
    </div>